#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SA1Guyingxiongkai

#include "Basic.hpp"

#include "ABP_SA1Guyingxiongkai_classes.hpp"
#include "ABP_SA1Guyingxiongkai_parameters.hpp"


namespace SDK
{

// Function ABP_SA1Guyingxiongkai.ABP_SA1Guyingxiongkai_C.ExecuteUbergraph_ABP_SA1Guyingxiongkai
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SA1Guyingxiongkai_C::ExecuteUbergraph_ABP_SA1Guyingxiongkai(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SA1Guyingxiongkai_C", "ExecuteUbergraph_ABP_SA1Guyingxiongkai");

	Params::ABP_SA1Guyingxiongkai_C_ExecuteUbergraph_ABP_SA1Guyingxiongkai Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_SA1Guyingxiongkai.ABP_SA1Guyingxiongkai_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_SA1Guyingxiongkai_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SA1Guyingxiongkai_C", "AnimGraph");

	Params::ABP_SA1Guyingxiongkai_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

