#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_MO1FengXYLMd00401_02

#include "Basic.hpp"

#include "AIC_MO1FengXYLMd00401_02_classes.hpp"
#include "AIC_MO1FengXYLMd00401_02_parameters.hpp"


namespace SDK
{

// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.ExecuteUbergraph_AIC_MO1FengXYLMd00401_02
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAIC_MO1FengXYLMd00401_02_C::ExecuteUbergraph_AIC_MO1FengXYLMd00401_02(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "ExecuteUbergraph_AIC_MO1FengXYLMd00401_02");

	Params::AIC_MO1FengXYLMd00401_02_C_ExecuteUbergraph_AIC_MO1FengXYLMd00401_02 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.合击目标重置
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::合击目标重置(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "合击目标重置");

	Params::AIC_MO1FengXYLMd00401_02_C_合击目标重置 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.限制解除
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::限制解除(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "限制解除");

	Params::AIC_MO1FengXYLMd00401_02_C_限制解除 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.进战重置
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::进战重置(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "进战重置");

	Params::AIC_MO1FengXYLMd00401_02_C_进战重置 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.派对散伙
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::派对散伙(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "派对散伙");

	Params::AIC_MO1FengXYLMd00401_02_C_派对散伙 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.群嘲派对
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::群嘲派对(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "群嘲派对");

	Params::AIC_MO1FengXYLMd00401_02_C_群嘲派对 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.嘲讽
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_MO1FengXYLMd00401_02_C::嘲讽(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "嘲讽");

	Params::AIC_MO1FengXYLMd00401_02_C_嘲讽 Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_MO1FengXYLMd00401_02.AIC_MO1FengXYLMd00401_02_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void AAIC_MO1FengXYLMd00401_02_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_MO1FengXYLMd00401_02_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

