#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_Floater_NM013

#include "Basic.hpp"

#include "AIC_Floater_NM013_classes.hpp"
#include "AIC_Floater_NM013_parameters.hpp"


namespace SDK
{

// Function AIC_Floater_NM013.AIC_Floater_NM013_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void AAIC_Floater_NM013_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIC_Floater_NM013.AIC_Floater_NM013_C.ShowUp
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bContent                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAIC_Floater_NM013_C::ShowUp(bool bContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "ShowUp");

	Params::AIC_Floater_NM013_C_ShowUp Parms{};

	Parms.bContent = bContent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_Floater_NM013.AIC_Floater_NM013_C.更新黑板值
// (BlueprintCallable, BlueprintEvent)

void AAIC_Floater_NM013_C::更新黑板值()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "更新黑板值");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIC_Floater_NM013.AIC_Floater_NM013_C.相机模式关闭
// (BlueprintCallable, BlueprintEvent)

void AAIC_Floater_NM013_C::相机模式关闭()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "相机模式关闭");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIC_Floater_NM013.AIC_Floater_NM013_C.相机模式开启
// (BlueprintCallable, BlueprintEvent)

void AAIC_Floater_NM013_C::相机模式开启()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "相机模式开启");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIC_Floater_NM013.AIC_Floater_NM013_C.ExecuteUbergraph_AIC_Floater_NM013
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAIC_Floater_NM013_C::ExecuteUbergraph_AIC_Floater_NM013(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_Floater_NM013_C", "ExecuteUbergraph_AIC_Floater_NM013");

	Params::AIC_Floater_NM013_C_ExecuteUbergraph_AIC_Floater_NM013 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

