#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AttackShake_Jinxi2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AttackShake_Jinxi2.AttackShake_Jinxi2_C
// 0x0000 (0x01A0 - 0x01A0)
class UAttackShake_Jinxi2_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AttackShake_Jinxi2_C">();
	}
	static class UAttackShake_Jinxi2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAttackShake_Jinxi2_C>();
	}
};
static_assert(alignof(UAttackShake_Jinxi2_C) == 0x000010, "Wrong alignment on UAttackShake_Jinxi2_C");
static_assert(sizeof(UAttackShake_Jinxi2_C) == 0x0001A0, "Wrong size on UAttackShake_Jinxi2_C");

}

