#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NA055

#include "Basic.hpp"

#include "BP_NA055_classes.hpp"
#include "BP_NA055_parameters.hpp"


namespace SDK
{

// Function BP_NA055.BP_NA055_C.ExecuteUbergraph_BP_NA055
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NA055_C::ExecuteUbergraph_BP_NA055(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NA055_C", "ExecuteUbergraph_BP_NA055");

	Params::BP_NA055_C_ExecuteUbergraph_BP_NA055 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NA055.BP_NA055_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NA055_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NA055_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

