#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VolumetricLight

#include "Basic.hpp"

#include "BP_VolumetricLight_classes.hpp"
#include "BP_VolumetricLight_parameters.hpp"


namespace SDK
{

// Function BP_VolumetricLight.BP_VolumetricLight_C.ExecuteUbergraph_BP_VolumetricLight
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VolumetricLight_C::ExecuteUbergraph_BP_VolumetricLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VolumetricLight_C", "ExecuteUbergraph_BP_VolumetricLight");

	Params::BP_VolumetricLight_C_ExecuteUbergraph_BP_VolumetricLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VolumetricLight.BP_VolumetricLight_C.SetLightIntensityScale
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   ScaleFactor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VolumetricLight_C::SetLightIntensityScale(float ScaleFactor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VolumetricLight_C", "SetLightIntensityScale");

	Params::BP_VolumetricLight_C_SetLightIntensityScale Parms{};

	Parms.ScaleFactor = ScaleFactor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VolumetricLight.BP_VolumetricLight_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_VolumetricLight_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VolumetricLight_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

