#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_LKK_Attack_5

#include "Basic.hpp"

#include "BP_CameraShakeAndForceFeedback_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_LKK_Attack_5.CS_LKK_Attack_5_C
// 0x0000 (0x01E0 - 0x01E0)
class UCS_LKK_Attack_5_C final : public UBP_CameraShakeAndForceFeedback_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CS_LKK_Attack_5_C">();
	}
	static class UCS_LKK_Attack_5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_LKK_Attack_5_C>();
	}
};
static_assert(alignof(UCS_LKK_Attack_5_C) == 0x000010, "Wrong alignment on UCS_LKK_Attack_5_C");
static_assert(sizeof(UCS_LKK_Attack_5_C) == 0x0001E0, "Wrong size on UCS_LKK_Attack_5_C");

}

