#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Destroy_Bianshen_Tafang

#include "Basic.hpp"

#include "GA_Destroy_Bianshen_Tafang_classes.hpp"
#include "GA_Destroy_Bianshen_Tafang_parameters.hpp"


namespace SDK
{

// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.ExecuteUbergraph_GA_Destroy_Bianshen_Tafang
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Destroy_Bianshen_Tafang_C::ExecuteUbergraph_GA_Destroy_Bianshen_Tafang(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "ExecuteUbergraph_GA_Destroy_Bianshen_Tafang");

	Params::GA_Destroy_Bianshen_Tafang_C_ExecuteUbergraph_GA_Destroy_Bianshen_Tafang Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Destroy_Bianshen_Tafang_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "K2_OnEndAbility");

	Params::GA_Destroy_Bianshen_Tafang_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.EventReceived_18B59F5945020DB23C42FD888A053E5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Destroy_Bianshen_Tafang_C::EventReceived_18B59F5945020DB23C42FD888A053E5B(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "EventReceived_18B59F5945020DB23C42FD888A053E5B");

	Params::GA_Destroy_Bianshen_Tafang_C_EventReceived_18B59F5945020DB23C42FD888A053E5B Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.EventReceived_18B59F5945020DB23C42FD88E496E330
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Destroy_Bianshen_Tafang_C::EventReceived_18B59F5945020DB23C42FD88E496E330(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "EventReceived_18B59F5945020DB23C42FD88E496E330");

	Params::GA_Destroy_Bianshen_Tafang_C_EventReceived_18B59F5945020DB23C42FD88E496E330 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.Added_21071CB943CD992BF8EFD6A3A875344A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Destroy_Bianshen_Tafang_C::Added_21071CB943CD992BF8EFD6A3A875344A(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "Added_21071CB943CD992BF8EFD6A3A875344A");

	Params::GA_Destroy_Bianshen_Tafang_C_Added_21071CB943CD992BF8EFD6A3A875344A Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.Added_21071CB943CD992BF8EFD6A33423B613
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Destroy_Bianshen_Tafang_C::Added_21071CB943CD992BF8EFD6A33423B613(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "Added_21071CB943CD992BF8EFD6A33423B613");

	Params::GA_Destroy_Bianshen_Tafang_C_Added_21071CB943CD992BF8EFD6A33423B613 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.OnCompleted_5D118C384AE61F1C80292E816AB68CC6
// (BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::OnCompleted_5D118C384AE61F1C80292E816AB68CC6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "OnCompleted_5D118C384AE61F1C80292E816AB68CC6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.OnBlendOut_5D118C384AE61F1C80292E816AB68CC6
// (BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::OnBlendOut_5D118C384AE61F1C80292E816AB68CC6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "OnBlendOut_5D118C384AE61F1C80292E816AB68CC6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.OnInterrupted_5D118C384AE61F1C80292E816AB68CC6
// (BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::OnInterrupted_5D118C384AE61F1C80292E816AB68CC6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "OnInterrupted_5D118C384AE61F1C80292E816AB68CC6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.OnCancelled_5D118C384AE61F1C80292E816AB68CC6
// (BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::OnCancelled_5D118C384AE61F1C80292E816AB68CC6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "OnCancelled_5D118C384AE61F1C80292E816AB68CC6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.OnTick_5D118C384AE61F1C80292E816AB68CC6
// (BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::OnTick_5D118C384AE61F1C80292E816AB68CC6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "OnTick_5D118C384AE61F1C80292E816AB68CC6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.显示玩家模型
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::显示玩家模型()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "显示玩家模型");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Destroy_Bianshen_Tafang.GA_Destroy_Bianshen_Tafang_C.变身结束_碰撞关系处理
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_Destroy_Bianshen_Tafang_C::变身结束_碰撞关系处理()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Destroy_Bianshen_Tafang_C", "变身结束_碰撞关系处理");

	UObject::ProcessEvent(Func, nullptr);
}

}

