#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ExitSkillTrigger_Jinxi_Passive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Passive_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ExitSkillTrigger_Jinxi_Passive.GA_ExitSkillTrigger_Jinxi_Passive_C
// 0x0008 (0x0578 - 0x0570)
class UGA_ExitSkillTrigger_Jinxi_Passive_C final : public UGa_Passive_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_ExitSkillTrigger_Jinxi_Passive_C; // 0x0570(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_ExitSkillTrigger_Jinxi_Passive(int32 EntryPoint);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_ExitSkillTrigger_Jinxi_Passive_C">();
	}
	static class UGA_ExitSkillTrigger_Jinxi_Passive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ExitSkillTrigger_Jinxi_Passive_C>();
	}
};
static_assert(alignof(UGA_ExitSkillTrigger_Jinxi_Passive_C) == 0x000008, "Wrong alignment on UGA_ExitSkillTrigger_Jinxi_Passive_C");
static_assert(sizeof(UGA_ExitSkillTrigger_Jinxi_Passive_C) == 0x000578, "Wrong size on UGA_ExitSkillTrigger_Jinxi_Passive_C");
static_assert(offsetof(UGA_ExitSkillTrigger_Jinxi_Passive_C, UberGraphFrame_GA_ExitSkillTrigger_Jinxi_Passive_C) == 0x000570, "Member 'UGA_ExitSkillTrigger_Jinxi_Passive_C::UberGraphFrame_GA_ExitSkillTrigger_Jinxi_Passive_C' has a wrong offset!");

}

