#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Skill01_Jinxi

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Skill01_Jinxi.GA_Skill01_Jinxi_C
// 0x0008 (0x0570 - 0x0568)
class UGA_Skill01_Jinxi_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Skill01_Jinxi_C;                 // 0x0568(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Skill01_Jinxi(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E81D8A0A9D8();
	void OnBlendOut_5D118C384AE61F1C80292E81D8A0A9D8();
	void OnInterrupted_5D118C384AE61F1C80292E81D8A0A9D8();
	void OnCancelled_5D118C384AE61F1C80292E81D8A0A9D8();
	void OnTick_5D118C384AE61F1C80292E81D8A0A9D8();
	void EventReceived_18B59F5945020DB23C42FD8825B6A318(const struct FGameplayEventData& Payload);
	void EventReceived_18B59F5945020DB23C42FD88C4B006DD(const struct FGameplayEventData& Payload);
	void OnCompleted_5D118C384AE61F1C80292E81D8D6CD82();
	void OnBlendOut_5D118C384AE61F1C80292E81D8D6CD82();
	void OnInterrupted_5D118C384AE61F1C80292E81D8D6CD82();
	void OnCancelled_5D118C384AE61F1C80292E81D8D6CD82();
	void OnTick_5D118C384AE61F1C80292E81D8D6CD82();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Skill01_Jinxi_C">();
	}
	static class UGA_Skill01_Jinxi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Skill01_Jinxi_C>();
	}
};
static_assert(alignof(UGA_Skill01_Jinxi_C) == 0x000008, "Wrong alignment on UGA_Skill01_Jinxi_C");
static_assert(sizeof(UGA_Skill01_Jinxi_C) == 0x000570, "Wrong size on UGA_Skill01_Jinxi_C");
static_assert(offsetof(UGA_Skill01_Jinxi_C, UberGraphFrame_GA_Skill01_Jinxi_C) == 0x000568, "Member 'UGA_Skill01_Jinxi_C::UberGraphFrame_GA_Skill01_Jinxi_C' has a wrong offset!");

}

