#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NinjaLiveGUI

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass NinjaLiveGUI.NinjaLiveGUI_C
// 0x0368 (0x0668 - 0x0300)
class UNinjaLiveGUI_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       BlinkingText1;                                     // 0x0308(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class USpinBox*                               Zero01_SpinBox_BrushSize;                          // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero02_SpinBox_BrushDensity;                       // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero03_SpinBox_BrushHardness;                      // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero04_SpinBox_BrushNoise;                         // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero05_SpinBox_BrushRnd;                           // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero06_SpinBox_BrushPersist;                       // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              Zero07_Checkbox_BrushInvert;                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero08_SpinBox_BrushDrag;                          // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero09_SpinBox_BrushPuncture;                      // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero10_SpinBox_SimFeedback;                        // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Zero11_Button_SimClear;                            // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero12_SpinBox_SimSpeed;                           // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero13_SpinBox_SimTurbulence;                      // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero14_SpinBox_VeloAmp;                            // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero15_SpinBox_VeloOffsetX;                        // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero16_SpinBox_VeloOffsetY;                        // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero17_SpinBox_VeloAmpNoise;                       // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero18_SpinBox_VeloDirNoise;                       // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero19_SpinBox_VeloDirNoiseSize;                   // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero20_SpinBox_VeloDirNoiseOffs;                   // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Zero21_ComboBox_VeloFromBitmap;                    // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero22_SpinBox_VeloRotate;                         // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero23_SpinBox_VeloOffset;                         // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero24_SpinBox_VeloTile;                           // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Zero24b_Border_Warning_VelocityFromBitmap;         // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero25_SimareaMoFx;                                // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero25_SimareaMoOffset;                            // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Zero26_ComboBox_DensFromBitmap;                    // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Zero26b_Border_Warning_DensityFromBitmap;          // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero27_SpinBox_DensityOffsetX;                     // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero28_SpinBox_DensityOffsetY;                     // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero29_SpinBox_DensityTile;                        // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Zero30_ComboBox_DensFromMaterial;                  // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero31_SpinBox_DensityFieldAmp;                    // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero32_SpinBox_DensityFieldAmpNois;                // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero33_SpinBox_DensityFieldAmpNoisOfs;             // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero34_SpinBox_DensityFieldAmpNoisTile;            // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero35_SpinBox_BouncyEdges;                        // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero36_SpinBox_SimEdgeFadePow;                     // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               Zero37_SpinBox_SimEdgeFadeWidth;                   // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Zero38_ComboBox_OutputMaterial;                    // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Zero39_Button_SavePaintBuffer;                     // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Zero40_Button_SaveSimBuffer;                       // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Zero41_TextBlock_MetaInfo;                         // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border;                                            // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Main0_StatusBorder;                                // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main1_Button_Minimize;                             // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              Main2_TooltipCheckBox;                             // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main3_Button_CloseProgram;                         // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Main4_ComboBox_MainMenu;                           // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Main5_ComboBox_Presets;                            // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main6_Button_OverWritePreset;                      // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main7_Button_DuplicatePreset;                      // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main8_Button_RemovePreset;                         // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Main9_Button_AutoLoadPreset;                       // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MenuFrame1;                                        // 0x04C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MenuFrame2;                                        // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MenuFrame3;                                        // 0x04D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMultiLineEditableText*                 MultiLineEditableText_MetaData;                    // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             NamedSlot_empty;                                   // 0x04E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             NamedSlot_FluidNinja;                              // 0x04F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_BRUSH;                                   // 0x04F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_FIELDS;                                  // 0x0500(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_SIM;                                     // 0x0508(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 SelectedProjectItem;                               // 0x0510(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 SelectedPresetItem;                                // 0x0520(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 SelectedPresetItemTemp;                            // 0x0530(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 NullString;                                        // 0x0540(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 DefaultSelection;                                  // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class UNamedSlot*>                     ArrayOfWidgets;                                    // 0x0560(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                         Counter;                                           // 0x0570(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SelectedActorIndex;                                // 0x0574(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PresetsDetected;                                   // 0x0578(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_579[0x7];                                      // 0x0579(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const class FString& SelectedMenuItem, const class FString& SelectedActorName)> OnSelectionChanged; // 0x0580(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const class FString& SelectedPreset, bool ForceAutoLoadPreset)> OnPresetSelectionChanged; // 0x0590(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const class FString& SelectedProject, const class FString& SelectedPreset, bool OverWriteOrNot)> OnPresetSave; // 0x05A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float                                         Timer;                                             // 0x05B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TimerTemp;                                         // 0x05B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NinjaBaseArraysConstructed;                        // 0x05B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          PresetSaveOverWriteFlag;                           // 0x05B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5BA[0x6];                                      // 0x05BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           TempVarOfParticleTemplatePackages;                 // 0x05C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           TempVarOfDensityTemplatePackages;                  // 0x05D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           TempVarOfVelocityTemplatePackages;                 // 0x05E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           TempVarOfOutputMaterials;                          // 0x05F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                         ArrayOfPresetNamesUnsorted;                        // 0x0600(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                         ArrayOfPresetNamesSorted;                          // 0x0610(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          SaveBasicAtlasPlayer;                              // 0x0620(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          SaveBasicFlowPlayer;                               // 0x0621(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          NinjaViewPortToolsVisibilityFlag;                  // 0x0622(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_623[0x5];                                      // 0x0623(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool SavePaintBuffer)> OnDensityMapSave;                           // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          SystemOn;                                          // 0x0638(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          RecordingStarted;                                  // 0x0639(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_63A[0x2];                                      // 0x063A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TempVecfieldIndex;                                 // 0x063C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UDataTable* DuplicatedPreset)> OnPresetDuplicated;           // 0x0640(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ForcePreferredPreset;                              // 0x0650(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_651[0x7];                                      // 0x0651(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 SelectedActor;                                     // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNinjaLiveComponent_C*                  SelectedActorComponent;                            // 0x0660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__SpinBox_Density2_K2Node_ComponentBoundEvent_3_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Density3_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Density4_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__45SpinBox_VeloFromSimAreaMotion_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__50ComboBox_NinjaOutputMaterial_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__24SpinBox_DirNoise_K2Node_ComponentBoundEvent_1_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__24SpinBox_DirNoise_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__41SpinBox_BrushPuncture_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Add01_K2Node_ComponentBoundEvent_1_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_Add01_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__AddCheckBox1_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__32SpinBox_DensSharpSize_K2Node_ComponentBoundEvent_41_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__31SpinBox_DensSharpen_K2Node_ComponentBoundEvent_40_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__29SpinBox_DensHue_K2Node_ComponentBoundEvent_38_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__28SpinBox_DensContrast_K2Node_ComponentBoundEvent_35_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__27SpinBox_DensShading_K2Node_ComponentBoundEvent_34_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__25SpinBox_DensInputWeight_K2Node_ComponentBoundEvent_32_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__24SpinBox_VeloNoise_K2Node_ComponentBoundEvent_31_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__22SpinBox_VeloAmplify_K2Node_ComponentBoundEvent_15_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__21SpinBox_VeloRotate_K2Node_ComponentBoundEvent_13_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__20SpinBox_VeloOffsetY_K2Node_ComponentBoundEvent_12_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__19SpinBox_VeloOffsetX_K2Node_ComponentBoundEvent_10_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_63_K2Node_ComponentBoundEvent_228_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_62_K2Node_ComponentBoundEvent_121_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__MultiLineEditableText_MetaData_K2Node_ComponentBoundEvent_26_OnMultiLineEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__SpinBox_60_K2Node_ComponentBoundEvent_225_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__ComboBox_NinjaTemplate3_K2Node_ComponentBoundEvent_224_OnOpeningEvent__DelegateSignature();
	void BndEvt__ComboBox_NinjaTemplate3_K2Node_ComponentBoundEvent_223_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__ComboBox_NinjaTemplate2_K2Node_ComponentBoundEvent_222_OnOpeningEvent__DelegateSignature();
	void BndEvt__ComboBox_NinjaTemplate2_K2Node_ComponentBoundEvent_120_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__ComboBox_NinjaTemplate1_K2Node_ComponentBoundEvent_220_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__SpinBox_26_K2Node_ComponentBoundEvent_128_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__Button_14_K2Node_ComponentBoundEvent_123_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SpinBox_22_K2Node_ComponentBoundEvent_102_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_23_K2Node_ComponentBoundEvent_100_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_19_K2Node_ComponentBoundEvent_70_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_18_K2Node_ComponentBoundEvent_94_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_17_K2Node_ComponentBoundEvent_78_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_16_K2Node_ComponentBoundEvent_76_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_15_K2Node_ComponentBoundEvent_74_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_14_K2Node_ComponentBoundEvent_72_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_12_K2Node_ComponentBoundEvent_64_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_11_K2Node_ComponentBoundEvent_60_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_10_K2Node_ComponentBoundEvent_55_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__Main9_Button_PreferredPreset_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void ExecuteUbergraph_NinjaLiveGUI(int32 EntryPoint);
	void BndEvt__50SpinBox_BrushNoise_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__Button_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SpinBox_0_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_0_K2Node_ComponentBoundEvent_1_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__21cSpinBox_VeloOffset_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__21cSpinBox_VeloOffset_K2Node_ComponentBoundEvent_1_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_DensityNoiseAmp_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_DensityNoiseAmp_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_DensityNoiseOffset_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_DensityNoiseOffset_K2Node_ComponentBoundEvent_5_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_DensityNoiseSize_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_DensityNoiseSize_K2Node_ComponentBoundEvent_7_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Feedback_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_Feedback_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Speed_K2Node_ComponentBoundEvent_5_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__SpinBox_Divergence_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__SpinBox_Divergence_K2Node_ComponentBoundEvent_7_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__Button_ClearBuffers_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__50bSpinBox_BrushRnd_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__025_SimareaMoOffset_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__Button_RemovePreset_K2Node_ComponentBoundEvent_218_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Button_152_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnInitialized();
	void BndEvt__Main3_Button_Minimize_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__CheckBox_21_K2Node_ComponentBoundEvent_219_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void OnPresetDuplicationFinished(class UDataTable* DuplicatedPreset);
	void BndEvt__Button_DuplicatePreset_K2Node_ComponentBoundEvent_217_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Button_SavePreset_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__ComboBox_Presets_K2Node_ComponentBoundEvent_36_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void BndEvt__ComboBoxString_89_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__ComboBoxString_89_K2Node_ComponentBoundEvent_2_OnOpeningEvent__DelegateSignature();
	void GetCurrentLevelInfoGUI(class FName* LevelName, class FName* LevelPath);
	void GetSelectedActor(int32 SelectedActorIndex_0, class ANinjaLive_C** NinjaLiveActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NinjaLiveGUI_C">();
	}
	static class UNinjaLiveGUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNinjaLiveGUI_C>();
	}
};
static_assert(alignof(UNinjaLiveGUI_C) == 0x000008, "Wrong alignment on UNinjaLiveGUI_C");
static_assert(sizeof(UNinjaLiveGUI_C) == 0x000668, "Wrong size on UNinjaLiveGUI_C");
static_assert(offsetof(UNinjaLiveGUI_C, UberGraphFrame) == 0x000300, "Member 'UNinjaLiveGUI_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, BlinkingText1) == 0x000308, "Member 'UNinjaLiveGUI_C::BlinkingText1' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero01_SpinBox_BrushSize) == 0x000310, "Member 'UNinjaLiveGUI_C::Zero01_SpinBox_BrushSize' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero02_SpinBox_BrushDensity) == 0x000318, "Member 'UNinjaLiveGUI_C::Zero02_SpinBox_BrushDensity' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero03_SpinBox_BrushHardness) == 0x000320, "Member 'UNinjaLiveGUI_C::Zero03_SpinBox_BrushHardness' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero04_SpinBox_BrushNoise) == 0x000328, "Member 'UNinjaLiveGUI_C::Zero04_SpinBox_BrushNoise' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero05_SpinBox_BrushRnd) == 0x000330, "Member 'UNinjaLiveGUI_C::Zero05_SpinBox_BrushRnd' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero06_SpinBox_BrushPersist) == 0x000338, "Member 'UNinjaLiveGUI_C::Zero06_SpinBox_BrushPersist' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero07_Checkbox_BrushInvert) == 0x000340, "Member 'UNinjaLiveGUI_C::Zero07_Checkbox_BrushInvert' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero08_SpinBox_BrushDrag) == 0x000348, "Member 'UNinjaLiveGUI_C::Zero08_SpinBox_BrushDrag' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero09_SpinBox_BrushPuncture) == 0x000350, "Member 'UNinjaLiveGUI_C::Zero09_SpinBox_BrushPuncture' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero10_SpinBox_SimFeedback) == 0x000358, "Member 'UNinjaLiveGUI_C::Zero10_SpinBox_SimFeedback' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero11_Button_SimClear) == 0x000360, "Member 'UNinjaLiveGUI_C::Zero11_Button_SimClear' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero12_SpinBox_SimSpeed) == 0x000368, "Member 'UNinjaLiveGUI_C::Zero12_SpinBox_SimSpeed' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero13_SpinBox_SimTurbulence) == 0x000370, "Member 'UNinjaLiveGUI_C::Zero13_SpinBox_SimTurbulence' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero14_SpinBox_VeloAmp) == 0x000378, "Member 'UNinjaLiveGUI_C::Zero14_SpinBox_VeloAmp' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero15_SpinBox_VeloOffsetX) == 0x000380, "Member 'UNinjaLiveGUI_C::Zero15_SpinBox_VeloOffsetX' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero16_SpinBox_VeloOffsetY) == 0x000388, "Member 'UNinjaLiveGUI_C::Zero16_SpinBox_VeloOffsetY' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero17_SpinBox_VeloAmpNoise) == 0x000390, "Member 'UNinjaLiveGUI_C::Zero17_SpinBox_VeloAmpNoise' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero18_SpinBox_VeloDirNoise) == 0x000398, "Member 'UNinjaLiveGUI_C::Zero18_SpinBox_VeloDirNoise' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero19_SpinBox_VeloDirNoiseSize) == 0x0003A0, "Member 'UNinjaLiveGUI_C::Zero19_SpinBox_VeloDirNoiseSize' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero20_SpinBox_VeloDirNoiseOffs) == 0x0003A8, "Member 'UNinjaLiveGUI_C::Zero20_SpinBox_VeloDirNoiseOffs' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero21_ComboBox_VeloFromBitmap) == 0x0003B0, "Member 'UNinjaLiveGUI_C::Zero21_ComboBox_VeloFromBitmap' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero22_SpinBox_VeloRotate) == 0x0003B8, "Member 'UNinjaLiveGUI_C::Zero22_SpinBox_VeloRotate' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero23_SpinBox_VeloOffset) == 0x0003C0, "Member 'UNinjaLiveGUI_C::Zero23_SpinBox_VeloOffset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero24_SpinBox_VeloTile) == 0x0003C8, "Member 'UNinjaLiveGUI_C::Zero24_SpinBox_VeloTile' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero24b_Border_Warning_VelocityFromBitmap) == 0x0003D0, "Member 'UNinjaLiveGUI_C::Zero24b_Border_Warning_VelocityFromBitmap' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero25_SimareaMoFx) == 0x0003D8, "Member 'UNinjaLiveGUI_C::Zero25_SimareaMoFx' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero25_SimareaMoOffset) == 0x0003E0, "Member 'UNinjaLiveGUI_C::Zero25_SimareaMoOffset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero26_ComboBox_DensFromBitmap) == 0x0003E8, "Member 'UNinjaLiveGUI_C::Zero26_ComboBox_DensFromBitmap' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero26b_Border_Warning_DensityFromBitmap) == 0x0003F0, "Member 'UNinjaLiveGUI_C::Zero26b_Border_Warning_DensityFromBitmap' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero27_SpinBox_DensityOffsetX) == 0x0003F8, "Member 'UNinjaLiveGUI_C::Zero27_SpinBox_DensityOffsetX' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero28_SpinBox_DensityOffsetY) == 0x000400, "Member 'UNinjaLiveGUI_C::Zero28_SpinBox_DensityOffsetY' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero29_SpinBox_DensityTile) == 0x000408, "Member 'UNinjaLiveGUI_C::Zero29_SpinBox_DensityTile' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero30_ComboBox_DensFromMaterial) == 0x000410, "Member 'UNinjaLiveGUI_C::Zero30_ComboBox_DensFromMaterial' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero31_SpinBox_DensityFieldAmp) == 0x000418, "Member 'UNinjaLiveGUI_C::Zero31_SpinBox_DensityFieldAmp' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero32_SpinBox_DensityFieldAmpNois) == 0x000420, "Member 'UNinjaLiveGUI_C::Zero32_SpinBox_DensityFieldAmpNois' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero33_SpinBox_DensityFieldAmpNoisOfs) == 0x000428, "Member 'UNinjaLiveGUI_C::Zero33_SpinBox_DensityFieldAmpNoisOfs' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero34_SpinBox_DensityFieldAmpNoisTile) == 0x000430, "Member 'UNinjaLiveGUI_C::Zero34_SpinBox_DensityFieldAmpNoisTile' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero35_SpinBox_BouncyEdges) == 0x000438, "Member 'UNinjaLiveGUI_C::Zero35_SpinBox_BouncyEdges' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero36_SpinBox_SimEdgeFadePow) == 0x000440, "Member 'UNinjaLiveGUI_C::Zero36_SpinBox_SimEdgeFadePow' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero37_SpinBox_SimEdgeFadeWidth) == 0x000448, "Member 'UNinjaLiveGUI_C::Zero37_SpinBox_SimEdgeFadeWidth' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero38_ComboBox_OutputMaterial) == 0x000450, "Member 'UNinjaLiveGUI_C::Zero38_ComboBox_OutputMaterial' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero39_Button_SavePaintBuffer) == 0x000458, "Member 'UNinjaLiveGUI_C::Zero39_Button_SavePaintBuffer' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero40_Button_SaveSimBuffer) == 0x000460, "Member 'UNinjaLiveGUI_C::Zero40_Button_SaveSimBuffer' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Zero41_TextBlock_MetaInfo) == 0x000468, "Member 'UNinjaLiveGUI_C::Zero41_TextBlock_MetaInfo' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Border) == 0x000470, "Member 'UNinjaLiveGUI_C::Border' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main0_StatusBorder) == 0x000478, "Member 'UNinjaLiveGUI_C::Main0_StatusBorder' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main1_Button_Minimize) == 0x000480, "Member 'UNinjaLiveGUI_C::Main1_Button_Minimize' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main2_TooltipCheckBox) == 0x000488, "Member 'UNinjaLiveGUI_C::Main2_TooltipCheckBox' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main3_Button_CloseProgram) == 0x000490, "Member 'UNinjaLiveGUI_C::Main3_Button_CloseProgram' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main4_ComboBox_MainMenu) == 0x000498, "Member 'UNinjaLiveGUI_C::Main4_ComboBox_MainMenu' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main5_ComboBox_Presets) == 0x0004A0, "Member 'UNinjaLiveGUI_C::Main5_ComboBox_Presets' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main6_Button_OverWritePreset) == 0x0004A8, "Member 'UNinjaLiveGUI_C::Main6_Button_OverWritePreset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main7_Button_DuplicatePreset) == 0x0004B0, "Member 'UNinjaLiveGUI_C::Main7_Button_DuplicatePreset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main8_Button_RemovePreset) == 0x0004B8, "Member 'UNinjaLiveGUI_C::Main8_Button_RemovePreset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Main9_Button_AutoLoadPreset) == 0x0004C0, "Member 'UNinjaLiveGUI_C::Main9_Button_AutoLoadPreset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, MenuFrame1) == 0x0004C8, "Member 'UNinjaLiveGUI_C::MenuFrame1' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, MenuFrame2) == 0x0004D0, "Member 'UNinjaLiveGUI_C::MenuFrame2' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, MenuFrame3) == 0x0004D8, "Member 'UNinjaLiveGUI_C::MenuFrame3' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, MultiLineEditableText_MetaData) == 0x0004E0, "Member 'UNinjaLiveGUI_C::MultiLineEditableText_MetaData' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, NamedSlot_empty) == 0x0004E8, "Member 'UNinjaLiveGUI_C::NamedSlot_empty' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, NamedSlot_FluidNinja) == 0x0004F0, "Member 'UNinjaLiveGUI_C::NamedSlot_FluidNinja' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TextBlock_BRUSH) == 0x0004F8, "Member 'UNinjaLiveGUI_C::TextBlock_BRUSH' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TextBlock_FIELDS) == 0x000500, "Member 'UNinjaLiveGUI_C::TextBlock_FIELDS' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TextBlock_SIM) == 0x000508, "Member 'UNinjaLiveGUI_C::TextBlock_SIM' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedProjectItem) == 0x000510, "Member 'UNinjaLiveGUI_C::SelectedProjectItem' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedPresetItem) == 0x000520, "Member 'UNinjaLiveGUI_C::SelectedPresetItem' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedPresetItemTemp) == 0x000530, "Member 'UNinjaLiveGUI_C::SelectedPresetItemTemp' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, NullString) == 0x000540, "Member 'UNinjaLiveGUI_C::NullString' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, DefaultSelection) == 0x000550, "Member 'UNinjaLiveGUI_C::DefaultSelection' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, ArrayOfWidgets) == 0x000560, "Member 'UNinjaLiveGUI_C::ArrayOfWidgets' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Counter) == 0x000570, "Member 'UNinjaLiveGUI_C::Counter' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedActorIndex) == 0x000574, "Member 'UNinjaLiveGUI_C::SelectedActorIndex' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, PresetsDetected) == 0x000578, "Member 'UNinjaLiveGUI_C::PresetsDetected' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, OnSelectionChanged) == 0x000580, "Member 'UNinjaLiveGUI_C::OnSelectionChanged' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, OnPresetSelectionChanged) == 0x000590, "Member 'UNinjaLiveGUI_C::OnPresetSelectionChanged' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, OnPresetSave) == 0x0005A0, "Member 'UNinjaLiveGUI_C::OnPresetSave' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, Timer) == 0x0005B0, "Member 'UNinjaLiveGUI_C::Timer' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TimerTemp) == 0x0005B4, "Member 'UNinjaLiveGUI_C::TimerTemp' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, NinjaBaseArraysConstructed) == 0x0005B8, "Member 'UNinjaLiveGUI_C::NinjaBaseArraysConstructed' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, PresetSaveOverWriteFlag) == 0x0005B9, "Member 'UNinjaLiveGUI_C::PresetSaveOverWriteFlag' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TempVarOfParticleTemplatePackages) == 0x0005C0, "Member 'UNinjaLiveGUI_C::TempVarOfParticleTemplatePackages' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TempVarOfDensityTemplatePackages) == 0x0005D0, "Member 'UNinjaLiveGUI_C::TempVarOfDensityTemplatePackages' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TempVarOfVelocityTemplatePackages) == 0x0005E0, "Member 'UNinjaLiveGUI_C::TempVarOfVelocityTemplatePackages' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TempVarOfOutputMaterials) == 0x0005F0, "Member 'UNinjaLiveGUI_C::TempVarOfOutputMaterials' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, ArrayOfPresetNamesUnsorted) == 0x000600, "Member 'UNinjaLiveGUI_C::ArrayOfPresetNamesUnsorted' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, ArrayOfPresetNamesSorted) == 0x000610, "Member 'UNinjaLiveGUI_C::ArrayOfPresetNamesSorted' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SaveBasicAtlasPlayer) == 0x000620, "Member 'UNinjaLiveGUI_C::SaveBasicAtlasPlayer' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SaveBasicFlowPlayer) == 0x000621, "Member 'UNinjaLiveGUI_C::SaveBasicFlowPlayer' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, NinjaViewPortToolsVisibilityFlag) == 0x000622, "Member 'UNinjaLiveGUI_C::NinjaViewPortToolsVisibilityFlag' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, OnDensityMapSave) == 0x000628, "Member 'UNinjaLiveGUI_C::OnDensityMapSave' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SystemOn) == 0x000638, "Member 'UNinjaLiveGUI_C::SystemOn' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, RecordingStarted) == 0x000639, "Member 'UNinjaLiveGUI_C::RecordingStarted' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, TempVecfieldIndex) == 0x00063C, "Member 'UNinjaLiveGUI_C::TempVecfieldIndex' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, OnPresetDuplicated) == 0x000640, "Member 'UNinjaLiveGUI_C::OnPresetDuplicated' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, ForcePreferredPreset) == 0x000650, "Member 'UNinjaLiveGUI_C::ForcePreferredPreset' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedActor) == 0x000658, "Member 'UNinjaLiveGUI_C::SelectedActor' has a wrong offset!");
static_assert(offsetof(UNinjaLiveGUI_C, SelectedActorComponent) == 0x000660, "Member 'UNinjaLiveGUI_C::SelectedActorComponent' has a wrong offset!");

}

