#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WriteDataTableInterface

#include "Basic.hpp"


namespace SDK::Params
{

// Function WriteDataTableInterface.WriteDataTableInterface_C.WriteDataTableFunction
// 0x0018 (0x0018 - 0x0000)
struct WriteDataTableInterface_C_WriteDataTableFunction final
{
public:
	class UDataTable*                             InputTable;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 InputData;                                         // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WriteDataTableInterface_C_WriteDataTableFunction) == 0x000008, "Wrong alignment on WriteDataTableInterface_C_WriteDataTableFunction");
static_assert(sizeof(WriteDataTableInterface_C_WriteDataTableFunction) == 0x000018, "Wrong size on WriteDataTableInterface_C_WriteDataTableFunction");
static_assert(offsetof(WriteDataTableInterface_C_WriteDataTableFunction, InputTable) == 0x000000, "Member 'WriteDataTableInterface_C_WriteDataTableFunction::InputTable' has a wrong offset!");
static_assert(offsetof(WriteDataTableInterface_C_WriteDataTableFunction, InputData) == 0x000008, "Member 'WriteDataTableInterface_C_WriteDataTableFunction::InputData' has a wrong offset!");

}

